## Vetores e Matrizes

In [2]:
import numpy as np

### Operações vetoriais

##### 1- Soma e Subtração

In [3]:
# Os vetores precisam ter a mesma dimensão. A soma acontece elemento por elemento.

vetor_1 = np.array([1,2,3])
vetor_2 = np.array([4,3,5])

print(f"Vetor 1: {vetor_1}")
print(f"\nVetor 2: {vetor_2}")

vetor_soma = vetor_1 + vetor_2
print(f"\n{vetor_1} + {vetor_2} = {vetor_soma}")

Vetor 1: [1 2 3]

Vetor 2: [4 3 5]

[1 2 3] + [4 3 5] = [5 5 8]


In [4]:
vetor_subtracao = vetor_1 - vetor_2
print(f"\n{vetor_1} + {vetor_2} = {vetor_subtracao}")


[1 2 3] + [4 3 5] = [-3 -1 -2]


##### 2- Multiplicação por escalar

In [5]:
# Nessa operação cada componente do vetor é multiplicado por um escalar (número) qualquer.

escalar1 = 3
escalar2 = -0.5

v = np.array([3,4,5])

print(f"{escalar1} x {v} = {escalar1 * v}")
print(f"\n{escalar2} x {v} = {escalar2 * v}")

3 x [3 4 5] = [ 9 12 15]

-0.5 x [3 4 5] = [-1.5 -2.  -2.5]


### Norma de um vetor

In [6]:
# A norma é basicamente o módulo (tamanho) do vetor, ou seja, a distância da origem até sua coordenada.
# Definição: Ela representa a distância euclidiana da origem do sistema de coordenadas (o ponto zero) até a coordenada final onde o vetor termina.

u = np.arange(1,10,0.5)
print("Vetor u:")
print(u)

norma_u = np.linalg.norm(u)

print(f'Norma de u: {norma_u:.2f}')

Vetor u:
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
Norma de u: 24.84


In [7]:
#Exemplo: Calcule a distância entre os vetores a = (3,6) e b = (5,2)

a = np.array([3,6])
b = np.array([5,2])

vetor_subtracao = a-b
print(f"{a} - {b} = {vetor_subtracao}")

#Distância: ||a-b||

d = np.linalg.norm(vetor_subtracao)

print(f"Distância entre {a} e {b} = {d:.2f}")

[3 6] - [5 2] = [-2  4]
Distância entre [3 6] e [5 2] = 4.47


### Produto Escalar/Interno

In [8]:
x = np.random.randint(1,5,5)
print(x)
y = np.random.randint(1,5,5)
print(y)

# Produto Escalar = <x,y> = x1*y1 + ... +xn*yn

dot_prod = np.dot(x,y)
print(f"<x,y> = {dot_prod}")

[2 3 1 2 1]
[1 2 2 4 3]
<x,y> = 21


### Ângulo entre vetores

In [9]:
u = np.array([1,2,3,4])

v = np.array([4,3,2,5])

dot_prod = np.dot(u,v)

norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)

print(f"Dot = {dot_prod}")
print(f"Norma u = {norm_u}")
print(f"Norm v = {norm_v}")

Dot = 36
Norma u = 5.477225575051661
Norm v = 7.3484692283495345


In [10]:
angulo_vetores_rad = np.arccos(dot_prod/(norm_u*norm_v))

angulo_vetores_graus = (angulo_vetores_rad*180)/np.pi

print(f"Angulo entre os vetores {u} e {v} = Rad:{angulo_vetores_rad} | Graus:{angulo_vetores_graus}")

Angulo entre os vetores [1 2 3 4] e [4 3 2 5] = Rad:0.46364760900080615 | Graus:26.56505117707799
