#### Introduction to Python Matrices and NumPy

##### 1 - Basics of NumPy

NumPy is the main package for scientific computing in Python. It performs a wide variety of advanced mathematical operations with high efficiency.

In [1]:
import numpy as np

In [2]:
one_dimensional_arr = np.array([10,12])
print(one_dimensional_arr)

[10 12]


In [3]:
# Create and print a NumPy array 'arr' containing the elements 1, 2 ,3.
arr = np.array([1,2,3])
print(arr)
print(f"Dimensão do array 'arr' = {arr.ndim}\n")

# Array 2D
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(f"Dimensão do array 'a' = {a.ndim}\n")

#Array 3D

b = np.array([[[1,2,3],[4,5,6],[1,2,3],[5,6,7]]])
print(b)
print(f"Dimensão do array 'b' = {b.ndim}")

[1 2 3]
Dimensão do array 'arr' = 1

[[1 2 3]
 [4 5 6]]
Dimensão do array 'a' = 2

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [5 6 7]]]
Dimensão do array 'b' = 3


Another way to implement an array is using np.arange(). This function will return an array of evenly spaced values within a given interval.

In [4]:
inicio = 1
passo = 0.5
final = 10

arr1 = np.arange(inicio, final + passo, passo)
print(arr1)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [5]:
# Create an array with 3 integers, starting from the default integer 0.
arr2 = np.arange(3)
print(arr2)

[0 1 2]


In [6]:
# Create an array that starts from the integer 1, ends at 20,incremented by 3. 
arr3 = np.arange(1,20,3, dtype = np.float16)
print(arr3)

[ 1.  4.  7. 10. 13. 16. 19.]


What if you wanted to create an array with five evenly spaced values in the interval from 0 to 100? As you may notice, you have 3 parameters that a function must take. One paremeter is the starting number, in this case 0, the final number 100 and the number of elements in the array, in this case, 5. NumPy has a function that allows you to do specifically this by using np.linspace()

In [7]:
lis_spaced_arr = np.linspace(0,100,5)
print(lis_spaced_arr)

[  0.  25.  50.  75. 100.]


In [8]:
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)

print(f"O dtype de 'char_arr' é {char_arr.dtype}")

['Welcome to Math for ML!']
O dtype de 'char_arr' é <U23


One of the advantages of using NumPy is that you can easily create arrays with built-in functions such as:

 - np.ones() - Returns a new array setting values to one.

In [9]:
ones_arr = np.ones((3,3))
print(ones_arr)

print("\n----------------------\n")

arr_example = np.arange(0,10)
print(arr_example)

print("\n----------------------\n")

ones_arr2 = np.ones_like(arr_example)
print(ones_arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

----------------------

[0 1 2 3 4 5 6 7 8 9]

----------------------

[1 1 1 1 1 1 1 1 1 1]


 - np.zeros() - Returns a new array setting values to zero.

In [10]:
zeros_arr = np.zeros((2,2))
print(zeros_arr)

print("\n----------------------\n")

zeros_arr2 = np.zeros(10)
print(zeros_arr2)

[[0. 0.]
 [0. 0.]]

----------------------

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


- np.empty() - Returns a new uninitialized array.

In [11]:
empt_arr = np.empty((3,3))
empt_arr[1][1] = 10
print(empt_arr)

[[ 1.  1.  1.]
 [ 1. 10.  1.]
 [ 1.  1.  1.]]


- np.random.rand() - Returns a new array with values chosen at random.

In [12]:
# Return a new array with random numbers between 0 and 1
rand_arr = np.random.rand(5,5)
print(rand_arr)

[[0.27687228 0.73693899 0.77102182 0.43761932 0.4626178 ]
 [0.25760149 0.83915239 0.46364997 0.13030414 0.7715013 ]
 [0.99055053 0.92801946 0.92972674 0.10463051 0.70391566]
 [0.52484266 0.63074338 0.25171937 0.52007958 0.65300996]
 [0.6912498  0.46278332 0.69879058 0.47454199 0.14859791]]


##### 2 - Multidimensional Arrays

With NumPy you can also create arrays with more than one dimension.

In [13]:
# Create a 2 dimensional array (2-D)
two_dim_arr = np.array([[1,2,3],[4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


An alternative way to create a multidimensional array is by reshaping the initial 1-D array. Using np.reshape() you can rearrange elements of the previous array into a new shape.

In [14]:
# 1-D array 
one_dim_arr = np.linspace(1,1000, 10)
print(one_dim_arr)

print("\n----------------------\n")

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
    one_dim_arr,  # the array to be reshaped
    (5,2) # dimensions of the new array
    )
print(multi_dim_arr)

[   1.  112.  223.  334.  445.  556.  667.  778.  889. 1000.]

----------------------

[[   1.  112.]
 [ 223.  334.]
 [ 445.  556.]
 [ 667.  778.]
 [ 889. 1000.]]


##### - Finding size, shape and dimension.

 - ndarray.ndim - Stores the number dimensions of the array.

In [15]:
arr = np.random.randint(1,100,(3,3))
print(arr)

# Dimension
print(arr.ndim)

[[70  9 88]
 [49 91 88]
 [33 59 23]]
2


- ndarray.shape - Stores the shape of the array. Each number in the tuple denotes the lengths of each corresponding dimension.

In [16]:
print(arr.shape)

(3, 3)


- ndarray.size - Stores the number of elements in the array.

In [17]:
# Returns total number of elements
print(arr.size)

9


##### 3 - Array math operations 

In [18]:
arr_1 = np.array([2,3,4])
arr_2 = np.array([1,2,3])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[3 5 7]
[1 1 1]
[ 2  6 12]


- Multiplying vector with a scalar (broadcasting)

In [19]:
# Suponha que este vetor possua diferentes velocidades em m/s e queremos transformar em k/h.
print("Velocidades em m/s: ")
vector_ms = np.random.randint(1,100,100)
print(vector_ms)

print("\nVelocidades em k/h: ")
vector_kh = (vector_ms * 3.6).copy()
print(vector_kh)

# This concept is called broadcasting, which allows you to perform operations specifically on arrays of different shapes.

Velocidades em m/s: 
[60 45 47 13 64 19 42 18 79 33 98 49 77 48 24 71 15 22 48 56 37 96 52 84
 65 63 85  1  5 47 28 62 50 85 68 50  9 26 71 41 26 19 33 30  5 37 94  2
 55 19 97 22 94 46  8 46 35 33 59 68 65 83 12 95 25 59 28 59 25 91  7 32
 95 45 13 90 46 62 38 44 57  4  8 73 53 85 53 84  4 43 22 32 95 79 87 18
  9 12 10 20]

Velocidades em k/h: 
[216.  162.  169.2  46.8 230.4  68.4 151.2  64.8 284.4 118.8 352.8 176.4
 277.2 172.8  86.4 255.6  54.   79.2 172.8 201.6 133.2 345.6 187.2 302.4
 234.  226.8 306.    3.6  18.  169.2 100.8 223.2 180.  306.  244.8 180.
  32.4  93.6 255.6 147.6  93.6  68.4 118.8 108.   18.  133.2 338.4   7.2
 198.   68.4 349.2  79.2 338.4 165.6  28.8 165.6 126.  118.8 212.4 244.8
 234.  298.8  43.2 342.   90.  212.4 100.8 212.4  90.  327.6  25.2 115.2
 342.  162.   46.8 324.  165.6 223.2 136.8 158.4 205.2  14.4  28.8 262.8
 190.8 306.  190.8 302.4  14.4 154.8  79.2 115.2 342.  284.4 313.2  64.8
  32.4  43.2  36.   72. ]


##### 4- Indexing and slicing

Indexing is very useful as it allows you to select specific elements from an array. It also lets you select entire rows/columns or planes as you'll see in future assignments for multidimensional arrays.


In [20]:
# Indexing:

arr_1d = np.linspace(1,10,20)
print(arr_1d)

# select the first element of the array
print(arr_1d[0])

# select the third element of the array
print(arr_1d[2])


[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
1.0
1.9473684210526314


In [21]:
arr_2d = np.random.randint(1,10,(3,3))
print(arr_2d)

print(arr_2d[0][0])

[[7 6 6]
 [2 9 7]
 [7 4 3]]
7


In [22]:
# Slicing:

#The syntax is: array[start:end:step]

# If no value is passed to start, it is assumed start = 0, if no value is passed for end, it is assumed that end = length of array and if no value is passed to step, it is assumed step = 1.

arr = np.array([1,2,3,4,5,6,7,8,9,10])

sliced_arr = arr[:5]

sliced_arr

array([1, 2, 3, 4, 5])

In [23]:
sliced_arr = arr[1::2]
sliced_arr

array([ 2,  4,  6,  8, 10])

In [24]:
sliced_arr = arr[::-1]
sliced_arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [25]:
arr = np.random.randint(0,10,(5,5))
arr

array([[8, 5, 3, 4, 7],
       [9, 3, 6, 7, 2],
       [6, 7, 0, 2, 4],
       [0, 1, 1, 5, 3],
       [2, 4, 5, 2, 9]], dtype=int32)

In [26]:
# The first row
sliced_arr = arr[:1]
sliced_arr

array([[8, 5, 3, 4, 7]], dtype=int32)

In [27]:
sliced_arr = arr[-1:]
sliced_arr

array([[2, 4, 5, 2, 9]], dtype=int32)

In [28]:
# The first column
sliced_arr = arr[:,0]
sliced_arr

array([8, 9, 6, 0, 2], dtype=int32)

In [29]:
sliced_arr = arr[3:,3:]
sliced_arr

array([[5, 3],
       [2, 9]], dtype=int32)

##### 5 - Stacking 

Finally, stacking is a feature of NumPy that leads to increased customization of arrays. It means to join two or more arrays, either horizontally or vertically, meaning that it is done along a new axis.

- np.vstack() - stacks vertically
- np.hstack() - stacks horizontally
- np.hsplit() - splits an array into several smaller arrays

In [30]:
a1 = np.random.randint(1,10,(2,2))
a2 = np.random.randint(1,10,(2,2))

print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[3 3]
 [4 9]]
a2:
[[4 4]
 [3 3]]


In [31]:
# Stack the arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)

[[3 3]
 [4 9]
 [4 4]
 [3 3]]


In [32]:
# Stack the arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[3 3 4 4]
 [4 9 3 3]]
