### **Aplicações de Autovalores e Autovetores**

In [3]:
import numpy as np
import matplotlib.pyplot as plt

<a name='1'></a>
## 1 - Application of Eigenvalues and Eigenvectors: Navigating Webpages

### Exercise 1

$$P=
\begin{bmatrix}
0    & 0.75 & 0.35 & 0.25 & 0.85 \\
0.15 & 0    & 0.35 & 0.25 & 0.05 \\
0.15 & 0.15 & 0    & 0.25 & 0.05 \\
0.15 & 0.05 & 0.05 & 0    & 0.05 \\
0.55 & 0.05 & 0.25 & 0.25 & 0
\end{bmatrix}\tag{5}
$$

In [4]:
# Matriz de Transição ou Matriz de markov:

P = np.array([
    [0, 0.75, 0.35, 0.25, 0.85],
    [0.15, 0, 0.35, 0.25, 0.05],
    [0.15, 0.15, 0, 0.25, 0.05],
    [0.15, 0.05, 0.05, 0, 0.05],
    [0.55, 0.05, 0.25, 0.25, 0]
])

print(f"Soma das colunas de P: {np.sum(P, axis = 0)}")
print(f"\nMatriz P:\n{P}")

Soma das colunas de P: [1. 1. 1. 1. 1.]

Matriz P:
[[0.   0.75 0.35 0.25 0.85]
 [0.15 0.   0.35 0.25 0.05]
 [0.15 0.15 0.   0.25 0.05]
 [0.15 0.05 0.05 0.   0.05]
 [0.55 0.05 0.25 0.25 0.  ]]


In [5]:
# Definindo o vetor X0, começando a navegação na página 4:

X0 = np.array([0,0,0,1,0]).reshape(-1,1)
print(X0)

[[0]
 [0]
 [0]
 [1]
 [0]]


In [6]:
# X1 = PX0

X1 = P @ X0

print(f"X1: \n{X1}")

X1: 
[[0.25]
 [0.25]
 [0.25]
 [0.  ]
 [0.25]]


Applying the transformation $m$ times you can find a vector $X_m$ with the probabilities of the browser being at each of the pages after $m$ steps of navigation.

In [7]:
X_i = np.array([0,0,0,1,0]).reshape(-1,1)
m = 100000

for i in range(m):

    X_i = P @ X_i

print(f"X_i: \n{X_i}")

X_i: 
[[0.39377747]
 [0.13393269]
 [0.11409081]
 [0.08512166]
 [0.27307736]]


Begin by finding eigenvalues and eigenvectors for the previously defined matrix $P$:

In [8]:
eigenvalues, eigenvectors = np.linalg.eig(P)

print(f"Eigenvalues: {eigenvalues}")
print(f"\nEigenvectors: \n{eigenvectors}")

Eigenvalues: [ 1.         -0.70367062  0.00539505 -0.08267227 -0.21905217]

Eigenvectors: 
[[-0.76088562 -0.81362074  0.10935376  0.14270615 -0.39408574]
 [-0.25879453  0.050269   -0.6653158   0.67528802 -0.66465044]
 [-0.2204546   0.07869601 -0.29090665  0.17007443  0.35048734]
 [-0.1644783   0.12446953  0.19740707 -0.43678067  0.23311487]
 [-0.52766004  0.56018621  0.64946163 -0.55128793  0.47513398]]


In general, a square matrix whose entries are all nonnegative, and the sum of the elements for each column is equal to $1$ is called a **Markov matrix**. Markov matrices have a handy property - they always have an eigenvalue equal to 1.

In [9]:
X_inf = eigenvectors[:,0]
print(f"Autovetor correspondente ao autovalor 1: \n{X_inf.reshape(-1,1)}")

Autovetor correspondente ao autovalor 1: 
[[-0.76088562]
 [-0.25879453]
 [-0.2204546 ]
 [-0.1644783 ]
 [-0.52766004]]


### Exercise 2

Just to verify the results, perform matrix multiplication $PX$ (multiply matrix `P` and vector `X_inf`) to check that the result will be equal to the vector $X$ (`X_inf`).

In [10]:
def check_eigenvector(P, X_inf):

    X_check = P @ X_inf

    return X_check

X_check = check_eigenvector(P, X_inf)

print(f"Autovetor correspondente ao autovalor 1: \n{X_inf}")

print(f"\nResultado da multiplicação: \n{X_check}")

# Comparação
print(f"\nResultado da comparação: {np.isclose(X_inf, X_check)}")

Autovetor correspondente ao autovalor 1: 
[-0.76088562 -0.25879453 -0.2204546  -0.1644783  -0.52766004]

Resultado da multiplicação: 
[-0.76088562 -0.25879453 -0.2204546  -0.1644783  -0.52766004]

Resultado da comparação: [ True  True  True  True  True]


In [13]:
# Tornando o vetor uma distribuição de probabilidade - vetor estocástico

X_inf = X_inf/sum(X_inf)
print(f"Long-run probabilities of being at each webpage:\n{X_inf.reshape(-1,1)}")


Long-run probabilities of being at each webpage:
[[0.39377747]
 [0.13393269]
 [0.11409081]
 [0.08512166]
 [0.27307736]]


Here is a fun fact: this type of a model was the foundation of the PageRank algorithm, which is the basis of Google's very successful search engine.