In [4]:
import numpy as np

<a name='1'></a>
## 1 - Representing and Solving a System of Linear Equations using Matrices

<a name='1.1'></a>
### 1.1 - System of Linear Equations

Here is a **system of linear equations** (or **linear system**) with three equations and three unknown variables:


$$\begin{cases} 
4x_1-3x_2+x_3=-10, \\ 2x_1+x_2+3x_3=0, \\ -x_1+2x_2-5x_3=17, \end{cases}\tag{1}$$

**To solve** this system of linear equations means to find such values of the variables $x_1$, $x_2$, $x_3$, that all of its equations are simultaneously satisfied.

<a name='1.2'></a>
### 1.2 - Solving Systems of Linear Equations using Matrices

In [ ]:
A = np.array([[4,-3,1],[2,1,3],[-1,2,-5]], dtype=np.dtype(float))
b = np.array([-10, 0, 17], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

try:

    x = np.linalg.solve(A,b)

except np.linalg.LinAlgError as err:

    print(err)

else:

    print(f"\nSolução do sistema: {x}")

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Array b:
[-10.   0.  17.]
Solução do sistema: [ 1.  4. -2.]


<a name='1.3'></a>
### 1.3 - Evaluating the Determinant of a Matrix

Matrix $A$ corresponding to the linear system $(1)$ is a **square matrix** - it has the same number of rows and columns. In the case of a square matrix it is possible to calculate its determinant - a real number that characterizes some properties of the matrix. A linear system containing three equations with three unknown variables will have one solution if and only if the matrix $A$ has a non-zero determinant.

Let's calculate the determinant using `np.linalg.det(A)` function:

In [8]:
det = np.linalg.det(A)

print(f"Determinat of matrix A: {det:.2f}")

Determinat of matrix A: -60.00


<a name='1.4'></a>
### 1.4 - What happens if the system has no unique solution?

Let's explore what happens if we use `np.linalg.solve` in a system with no unique solution (no solution at all or infinitely many solutions).

Given another system of linear equations:

$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 2x_1+x_2+5x_3=0, \end{cases}\tag{2}$$

let's find the determinant of the corresponding matrix.

In [14]:
B = np.array([[1,1,1],[0,1,-3],[2,1,5]], dtype=np.dtype(float))

b = np.array([2,1,0], dtype=np.dtype(float))

print("Matrix B:")
print(A)
print("\nArray b:")
print(b)

det = np.linalg.det(B)

print(f"\nDeterminant of the matrix B: {det:.2f}")

if np.isclose(det,0):

    print("System Singular")

else:

    print("System Non-Singular")

Matrix B:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Array b:
[2. 1. 0.]

Determinant of the matrix B: 0.00
System Singular


In [15]:
try:

    x = np.linalg.solve(B,b)

except np.linalg.LinAlgError as err:

    print(err)

else:

    print(f"\nSolução do sistema: {x}")

Singular matrix
