# Processo de Gram-Schmidt

In [107]:
import numpy as np

In [108]:
def dot_product(u,v):
    return np.dot(u,v)

def norm(u):
    return np.linalg.norm(u)

In [109]:
def ortogonalizacao(base):

    w1 = base[0]
    n = len(base)

    w = np.empty((n,len(base[0])))
    w[0] = w1

    for i in range(1, n):

        v_i = base[i]
        w_i = v_i.copy()

        for j in range(i):

            proj = (dot_product(v_i , w[j])/norm(w[j])**2) * w[j]

            w_i = w_i - proj

        w[i] = w_i

    return w

In [110]:
def ortonormalizacao(base):

    w = ortogonalizacao(base)

    for i in range(len(w)):

        w[i] = w[i] / norm(w[i])

    return w

In [111]:
b_R2 = np.array([[1,0],[1,1]])
b_R3 = np.array([[1,0,0], [1,1,0],[1,1,1]])

In [112]:
b_R2_ortogonal = ortogonalizacao(b_R2)
print(b_R2_ortogonal)

[[1. 0.]
 [0. 1.]]


In [113]:
b_R3_ortogonal = ortogonalizacao(b_R3)
print(b_R3_ortogonal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [114]:
base = np.array([
    [2, 1],
    [-1, 2]
], dtype=float)

# Verificação
W = ortonormalizacao(base)

print(dot_product(W[0], W[1]) )      
print(norm(W[0]))      
print(norm(W[1])  )    

print(f"\nW (Base ortonormal) = \n{W}")


0.0
0.9999999999999999
0.9999999999999999

W (Base ortonormal) = 
[[ 0.89442719  0.4472136 ]
 [-0.4472136   0.89442719]]


In [115]:
base = np.array([
    [1, 1, 0],
    [1, 0, 1],
    [0, 1, 1]
], dtype=float)

W_ortogonal = ortogonalizacao(base)
W_ortonormal = ortonormalizacao(base)

print(f"\nW (Base ortogonal) = \n{W_ortogonal}")
print(f"\nW (Base ortonormal) = \n{W_ortonormal}")

print(dot_product(W_ortonormal[0], W_ortonormal[1]))
print(dot_product(W_ortonormal[0], W_ortonormal[2])) 
print(dot_product(W_ortonormal[1], W_ortonormal[2]))


W (Base ortogonal) = 
[[ 1.          1.          0.        ]
 [ 0.5        -0.5         1.        ]
 [-0.66666667  0.66666667  0.66666667]]

W (Base ortonormal) = 
[[ 0.70710678  0.70710678  0.        ]
 [ 0.40824829 -0.40824829  0.81649658]
 [-0.57735027  0.57735027  0.57735027]]
1.1102230246251565e-16
1.6653345369377348e-16
-1.6653345369377348e-16
