# Matrix Multiplication

In [1]:
import numpy as np

<a name='1'></a>
## 1 - Definition of Matrix Multiplication

If $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix, the matrix product $C = AB$ (denoted without multiplication signs or dots) is defined to be the $m \times p$ matrix such that 
$$c_{ij}=a_{i1}b_{1j}+a_{i2}b_{2j}+\ldots+a_{in}b_{nj}=\sum_{k=1}^{n} a_{ik}b_{kj}, \tag{4}$$

where $a_{ik}$ are the elements of matrix $A$, $b_{kj}$ are the elements of matrix $B$, and $i = 1, \ldots, m$, $k=1, \ldots, n$, $j = 1, \ldots, p$. In other words, $c_{ij}$ is the dot product of the $i$-th row of $A$ and the $j$-th column of $B$.

<a name='2'></a>
## 2 - Matrix Multiplication using Python

In [9]:
a = [
    [1,2,3],
    [4,2,1],
    [3,2,1]
]

b = [
    [3,3,3],
    [1,2,1],
    [-3,-1,2]
]

print(a)
print(b)

[[1, 2, 3], [4, 2, 1], [3, 2, 1]]
[[3, 3, 3], [1, 2, 1], [-3, -1, 2]]


### Python

In [13]:
def matrix_multiplication(A,B):

    m = len(A)

    p = len(B[0])

    if len(A[0]) != len(B):

        return "Incompatible Matrices"
    
    n = len(b)
    
    matrix_result = []
    
    for i in range(m):

        row = []

        for j in range(p):

            sum = 0.0

            for k in range(n):

                sum += A[i][k] * B[k][j]

            row.append(sum)

        matrix_result.append(row)

    return matrix_result

def display_matrix(A):

    for r in A:

        print(r)

m = matrix_multiplication(a,b)

display_matrix(m)


[-4.0, 4.0, 11.0]
[11.0, 15.0, 16.0]
[8.0, 12.0, 13.0]


### NumPy

In [15]:
A = np.array(a)
print("Matrix A: ")
print(A)

B = np.array(b)
print("\nMatrix B: ")
print(B)

Matrix A: 
[[1 2 3]
 [4 2 1]
 [3 2 1]]

Matrix B: 
[[ 3  3  3]
 [ 1  2  1]
 [-3 -1  2]]


In [16]:
AB = np.matmul(A,B)

print("Matrix AB: ")
print(AB)

Matrix AB: 
[[-4  4 11]
 [11 15 16]
 [ 8 12 13]]


In [17]:
AB = A @ B
print("Matrix AB: ")
print(AB)

Matrix AB: 
[[-4  4 11]
 [11 15 16]
 [ 8 12 13]]


In [18]:
C = np.array([[4, 9, 9], [9, 1, 6], [9, 2, 3]])
print("Matrix A (3 by 3):\n", C)
D = np.array([[2, 2], [5, 7], [4, 4]])
print("Matrix B (3 by 2):\n", D)

Matrix A (3 by 3):
 [[4 9 9]
 [9 1 6]
 [9 2 3]]
Matrix B (3 by 2):
 [[2 2]
 [5 7]
 [4 4]]


In [19]:
np.matmul(C,D)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [20]:
C @ D

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

<a name='3'></a>
## 3 - Matrix Convention and Broadcasting
Mathematically, matrix multiplication is defined only if number of the columns of matrix $A$ is equal to the number of the rows of matrix $B$.

In [ ]:
C = np.array([[4, 9, 9], [9, 1, 6], [9, 2, 3]])
print("Matrix A (3 by 3):\n", C)
D = np.array([[2, 2], [5, 7], [4, 4]])
print("Matrix B (3 by 2):\n", D)

In [21]:
try:

    np.matmul(D,C)

except ValueError as err:

    print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [24]:
try:
    D @ C
except ValueError as err:
    print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [29]:
print(f"Shape C: {C.shape}")
print(f"Shape D: {D.shape}")

Shape C: (3, 3)
Shape D: (3, 2)


In [ ]:
x = np.array([1, -2, -5])
y = np.array([4, 3, -1])

# Dot Product
np.matmul(x,y)

np.int64(3)

In [33]:
np.dot(x,y)

np.int64(3)

In [38]:
A = np.array(a)
print("Matrix A: ")
print(A)

B = np.array(b)
print("\nMatrix B: ")
print(B)

print(f"\nAB :\n{np.dot(A,B)}")

Matrix A: 
[[1 2 3]
 [4 2 1]
 [3 2 1]]

Matrix B: 
[[ 3  3  3]
 [ 1  2  1]
 [-3 -1  2]]

AB :
[[-4  4 11]
 [11 15 16]
 [ 8 12 13]]
