# Gaussian Elimination

In [1]:
import numpy as np

In [2]:
def augmented_matrix(A,b):

    M = np.hstack((A, b.reshape((len(A[0:]), 1))))

    return M

A = np.array([[2,3,5],[-3,-2,4],[1,1,-2]])
b = np.array([12,-2,8])

augmented_A = augmented_matrix(A,b)

print(augmented_A)    

solution = np.linalg.solve(A,b)

print(f"Solução do sistema: {solution}")

[[ 2  3  5 12]
 [-3 -2  4 -2]
 [ 1  1 -2  8]]
Solução do sistema: [-14.          17.27272727  -2.36363636]


In [3]:
def trocar_linhas(A, row1, row2):

    M = A.copy()

    M[[row1,row2]] = M[[row2, row1]]

    return M

A_swapped = trocar_linhas(A, 0 ,2)

print(A_swapped)

[[ 1  1 -2]
 [-3 -2  4]
 [ 2  3  5]]


In [4]:
def encontrar_index_pivo_coluna(A, column):

    array = A[:,column]

    for i , value in enumerate(array):

        if not np.isclose(value, 0):

            return i
        
    return -1

N = np.array([
[0, 5, -3 ,6 ,8],
[0, 6, 3, 8, 1],
[0, 0, 0, 0, 0],
[0, 0, 0 ,0 ,7],
[0, 2, 1, 0, 4]
]
)
print(N)

index_pivo_col = encontrar_index_pivo_coluna(N, 0)

print(index_pivo_col)

[[ 0  5 -3  6  8]
 [ 0  6  3  8  1]
 [ 0  0  0  0  0]
 [ 0  0  0  0  7]
 [ 0  2  1  0  4]]
-1


In [5]:
def encontrar_index_pivo_linha(N, row, aumentada = False):

    M = N.copy()

    if aumentada == True:

        M = M[:,:-1]

    array = M[row]

    for i, value in enumerate(array):

        if not np.isclose(value, 0):

            return i
        
    return -1

index_pivo_lin = encontrar_index_pivo_linha(N,3)

print(index_pivo_lin)

4


In [6]:
index_pivo_lin = encontrar_index_pivo_linha(N, 3, True)

print(index_pivo_lin)


-1


# Row echelon form

In [7]:
def forma_escalonada(A,b):

    det = np.linalg.det(A)

    if np.isclose(det,0):

        return "Sistema Singular"
    
    A = A.copy()
    b = b.copy()

    A = A.astype('float64')
    b = b.astype('float64')
    
    M = augmented_matrix(A,b)

    qtd_linhas = len(A)

    for linha in range(qtd_linhas):

        candidato_pivo = M[linha,linha]

        if np.isclose(candidato_pivo,0) == True:

            index_col = encontrar_index_pivo_coluna(M, linha)

            M = trocar_linhas(M, linha, index_col)

            pivo = M[linha,linha]

        else:

            pivo = candidato_pivo

        
        M[linha] = (1/pivo) * M[linha]


        for j in range(linha+1, qtd_linhas):

            proximo_pivo = M[j,linha]

            M[j] = M[j] - proximo_pivo * M[linha]


    return M


In [8]:
A = np.array([[2,3,5],[-3,-2,4],[1,1,-2]])
b = np.array([12,-2,8])

print("Matriz A: ")
print(A)
print("\nVetor b: ")
print(b)

A_escalonada = forma_escalonada(A,b)

print("\nMatriz A aumentada e escalonada: ")
print(A_escalonada)

Matriz A: 
[[ 2  3  5]
 [-3 -2  4]
 [ 1  1 -2]]

Vetor b: 
[12 -2  8]

Matriz A aumentada e escalonada: 
[[ 1.          1.5         2.5         6.        ]
 [ 0.          1.          4.6         6.4       ]
 [-0.         -0.          1.         -2.36363636]]


<a name="5"></a>
## Back substitution

In [9]:
def back_substitution(M):

    qtd_linha = M.shape[0]

    for linha in reversed(range(qtd_linha)):

        linha_pivo = M[linha,:]

        index = encontrar_index_pivo_linha(M, linha, True)

        for j in range(linha):

            linha_para_reduzir = M[j,:]

            valor = linha_para_reduzir[index]

            linha_para_reduzir = linha_para_reduzir - valor * linha_pivo

            M[j,:] = linha_para_reduzir

    solucao = M[:,-1]

    return M, solucao

In [10]:
A = np.array([[0,3,5],[-3,-2,4],[1,1,-2]])
b = np.array([12,-2,8])

print("Matriz A: ")
print(A)
print("\nVetor b: ")
print(b)
print(f"Solucao = {np.linalg.solve(A,b)}")

A_escalonada = forma_escalonada(A,b)

print("\nMatriz A aumentada e escalonada: ")
print(A_escalonada)

A_escalonada_completa, x = back_substitution(A_escalonada)

print("Matriz escalonada por gauss jordan: ")
print(A_escalonada_completa)

print(f"\nSolucao do sistema: {x}")

Matriz A: 
[[ 0  3  5]
 [-3 -2  4]
 [ 1  1 -2]]

Vetor b: 
[12 -2  8]
Solucao = [-14.          12.18181818  -4.90909091]

Matriz A aumentada e escalonada: 
[[ 1.          0.66666667 -1.33333333  0.66666667]
 [ 0.          1.          1.66666667  4.        ]
 [-0.         -0.          1.         -4.90909091]]
Matriz escalonada por gauss jordan: 
[[  1.           0.           0.         -14.        ]
 [  0.           1.           0.          12.18181818]
 [ -0.          -0.           1.          -4.90909091]]

Solucao do sistema: [-14.          12.18181818  -4.90909091]
