In [2]:
import numpy as np

In [7]:
def solve_system_of_equations(A,b):

    try:

        solution = np.linalg.solve(A,b)

        return solution
    
    except np.linalg.LinAlgError as err:

        return -1
    
def augmented_matrix(A,b):

    M = np.hstack((A,b.reshape((len(A[:,0]),1))))

    return M.astype('float')

def get_index_first_non_zero_value_from_row(A, row, augmented = False):

    M = A.copy()

    if augmented == True:

        M = M[:,:-1]

    array_row = M[row]

    for i, v in enumerate(array_row):

        if not np.isclose(v, 0):

            return i
        
    return -1

def get_index_first_non_zero_value_from_column(A, column):

    M = A.copy()

    array_col = M[:,column]

    for i, v in enumerate(array_col):

        if not np.isclose(v, 0):

            return i
        
    return -1

def swap_lines(A, row1, row2):

    A[[row1,row2]] == A[[row2, row1]]

    return A
    
def gaussian_elimination(A,b):

    M = augmented_matrix(A,b)

    if solve_system_of_equations == -1:

        return "System has no unique solution"
    
    n = len(M)

    for i in range(n):

        pivot_candidate = M[i][i]

        if np.isclose(pivot_candidate, 0):

            index_element_non_zero = get_index_first_non_zero_value_from_column(M, i, True)

            M = swap_lines(M, i, index_element_non_zero)

            pivot = M[i][i]

        else:

            pivot = pivot_candidate

        
        M[i] = (1/pivot) * M[i]

        for j in range(i+1, n):

            value = M[j,i]

            M[j] = M[j] - value * M[i]


    return M

def back_substitution(N):

    M = N.copy()

    n = M.shape[0]

    for i in reversed(range(n)):

        row_pivot = M[i,:]

        index = get_index_first_non_zero_value_from_row(M, i, augmented = True)

        for j in range(i):

            row_above = M[j,:]

            value = row_above[index]

            row_above = row_above - value * row_pivot

            M[j,:] = row_above

    solution = M[:,-1]

    return solution, M

# Exemplo:
A = np.array([
    [3,-1,-1],
    [1, 1,0],
    [2, 0,-3]
])

b = np.array([5,0,2])

print("Matriz A:")
print(A)
print(f"\nArray b:")
print(b)
print("\nSolução: ")
print(solve_system_of_equations(A,b))


Matriz A:
[[ 3 -1 -1]
 [ 1  1  0]
 [ 2  0 -3]]

Array b:
[5 0 2]

Solução: 
[ 1.3 -1.3  0.2]


In [6]:
N = gaussian_elimination(A,b)
print("Matriz escalonada: ")
print(N)

solution, N_jorgan = back_substitution(N)
print("\nMatriz Escalonada Reduzida: ")
print(N_jorgan)

print("\nSolução: ")
print(solution)

Matriz escalonada: 
[[ 1.         -0.33333333 -0.33333333  1.66666667]
 [ 0.          1.          0.25       -1.25      ]
 [-0.         -0.          1.          0.2       ]]

Matriz Escalonada Reduzida: 
[[ 1.   0.   0.   1.3]
 [ 0.   1.   0.  -1.3]
 [-0.  -0.   1.   0.2]]

Solução: 
[ 1.3 -1.3  0.2]
